DROP DATABASE IF EXISTS EXERCICIO11 ;

CREATE DATABASE EXERCICIO11;

USE EXERCICIO11;

CREATE TABLE REGISTRO (
ID_RENAVAM INT NOT NULL,
ID_VEICULO INT NOT NULL,
PRIMARY KEY(ID_RENAVAM, ID_VEICULO)

 );
 
