DROP DATABASE IF EXISTS EXERCICIO13 ;

CREATE DATABASE EXERCICIO13;

USE EXERCICIO13;

CREATE TABLE PRODUTO (
ID_PRODUTO INT NOT NULL,
PRIMARY KEY(ID_PRODUTO)

 );
 
 CREATE TABLE PEDIDO(
 ID_PEDIDO INT NOT NULL,
 ID_PRODUTO INT,
PRIMARY KEY(ID_PEDIDO),
FOREIGN KEY(ID_PRODUTO)references PRODUTO(ID_PRODUTO)

 );