DROP DATABASE IF EXISTS EXERCICO15 ;

CREATE DATABASE EXERCICO15;

USE EXERCICO15;

CREATE TABLE IDENTIFICACAO (
ID_IDENTIFICACAO INT NOT NULL,
PRIMARY KEY(ID_IDENTIFICACAO)

 );
 CREATE TABLE DEPARTAMENTO(
 ID_DEPARTAMENTO INT NOT NULL,
 ID_IDENTIFICACAO INT,
PRIMARY KEY(ID_DEPARTAMENTO),
FOREIGN KEY(ID_IDENTIFICACAO)references IDENTIFICACAO(ID_IDENTIFICACAO)
 );