-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO05;

-- CRIANDO A BASE DE DADOS
CREATE DATABASE DBEXERCICIO05;

-- CONECTANDO NA BASE DE DADOS
USE DBEXERCICIO05;

CREATE TABLE Carro (
  idCarro INT ,
  Marca VARCHAR(45) ,
  Modelo VARCHAR(45) ,
  Anodefabricacao INT ,
  AnodeModelo INT ,
  Placa VARCHAR(8) ,
  Cor VARCHAR(45) ,
  Numerodochassi INT ,
  PRIMARY KEY (`idCarro`))


