DROP DATABASE IF EXISTS  EXERCICIO14 ;

CREATE DATABASE EXERCICIO14;

USE EXERCICIO14;

CREATE TABLE USUARIO (
ID_USUARIO INT NOT NULL,
PRIMARY KEY(ID_USUARIO)

 );
 CREATE TABLE VIDEO(
 ID_VIDEO INT NOT NULL,
PRIMARY KEY(ID_VIDEO)
 );
 CREATE TABLE ACESSO(
 ID_USUARIO INT NOT NULL,
 ID_VIDEO INT NOT NULL,
 PRIMARY KEY (ID_USUARIO, ID_VIDEO),
FOREIGN KEY(ID_USUARIO) references USUARIO(ID_USUARIO),
FOREIGN KEY(ID_VIDEO) references VIDEO(ID_VIDEO)
);
