-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO10;

-- CRIANDO A BASE DE DADOS
CREATE DATABASE DBEXERCICIO10;

-- CONECTANDO NA BASE DE DADOS
USE DBEXERCICIO10;

-- CRIANDO AS TABELAS
CREATE TABLE ARTESA (
 IDARTESA INT NOT NULL AUTO_INCREMENT
,NOME VARCHAR(45)
,EMAIL varchar(45)
,SEXO char(1)
,SENHA VARCHAR(45)
,CELULAR VARCHAR(15)
,RUA VARCHAR(150)
,NUMERO INT
,BAIRRO VARCHAR(45)
,CEP VARCHAR(8)
,CIDADE VARCHAR(45)
,ESTADO CHAR(2)
,PRIMARY KEY (IDARTESA)
);