DROP database IF EXISTS DBEXERCICIO10;

-- CRIANDO A BASE DE DADOS
CREATE DATABASE DBEXERCICIO10;

-- CONECTANDO NA BASE DE DADOS
USE DBEXERCICIO10;

-- CRIANDO AS TABELAS
CREATE TABLE PRODUTO (
 IDPRODUTO INT NOT NULL AUTO_INCREMENT
,NOME VARCHAR(45)
,DESCRICAO varchar(150)
,TIPO ENUM("REDE","TAPETE")
,VALOR NUMERIC(8,2)
,PRIMARY KEY (IDPRODUTO)
);