-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO09;

-- CRIANDO A BASE DE DADOS
CREATE DATABASE DBEXERCICIO09;

-- CONECTANDO NA BASE DE DADOS
USE DBEXERCICIO09;

-- CRIANDO AS TABELAS
CREATE TABLE ANIMAL (
IDANIMAL INT NOT NULL AUTO_INCREMENT
,TIPO ENUM("CÃO","GATO")
,PORTE varchar(15)
,SEXO char(1)
,NOME VARCHAR(45)
,PRIMARY KEY (IDANIMAL)

);