-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO09;

-- CRIANDO A BASE DE DADOS
CREATE DATABASE DBEXERCICIO09;

-- CONECTANDO NA BASE DE DADOS
USE DBEXERCICIO09;

-- CRIANDO AS TABELAS
CREATE TABLE CADIDATO (
 IDCANDIDATO INT NOT NULL AUTO_INCREMENT
,NOME VARCHAR(45)
,EMAIL varchar(45)
,SEXO char(1)
,SENHA VARCHAR(45)
,TELEFONE_1 VARCHAR(15)
,TELEFONE_2 VARCHAR(15)
,TELEFONE_3 VARCHAR(15)
,PRIMARY KEY (IDCANDIDATO)
);