-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO04;

-- CRIANDO A BASE DE DADOS
CREATE DATABASE DBEXERCICIO04;

-- CONECTANDO NA BASE DE DADOS
USE DBEXERCICIO04;

-- CRIANDO AS TABELAS
CREATE TABLE Usuario (
  Codigo INT NOT NULL,
  Username VARCHAR(45) ,
  Email VARCHAR(100) ,
  Invocador VARCHAR(24) ,
  Time VARCHAR(45) ,
  Senha VARCHAR(45) ,
  PRIMARY KEY (`Codigo`));


-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO04;

-- CRIANDO A BASE DE DADOS
CREATE DATABASE DBEXERCICIO04;

-- CONECTANDO NA BASE DE DADOS
USE DBEXERCICIO04;

-- CRIANDO AS TABELAS
CREATE TABLE team (
  idteam INT NOT NULL,
  Nome VARCHAR(45) ,
  tag VARCHAR(100) ,
  Logo VARCHAR(24) ,
  PRIMARY KEY (`idteam`))



