DROP DATABASE IF EXISTS DBEXERCICIO07;
CREATE DATABASE DBEXERCICIO07;

USE DBEXERCICIO07;

CREATE TABLE ALUNO (
  IDALUNO INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(100),
  DATA_NASCI DATE,
  NUMERO_CEL  INT,
  DDD_CEL INT,
  NUMERO_RESI  INT,
  DDD_RESI INT,
  NUMERO_CONT  INT,
  DDD_CONT INT,
  NUMERO_CONTATO varchar(100),
  PRIMARY KEY (IDALUNO)
  );
 