DROP DATABASE IF EXISTS DBEXERCICIO08;
CREATE DATABASE DBEXERCICIO08;

USE DBEXERCICIO08;

CREATE TABLE CADASTRO (
  IDCADASTRO INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(100),
  EMAIL VARCHAR(100),
  CIDADE VARCHAR(45),
  ESTADO CHAR(2),
  SEXO CHAR(1),
  ANIVERSARIO DATE,
  TELEFONE_1 INT,
  TELEFONE_2 INT,
  TELEFONE_3 INT,
  ENDERECO_COMP varchar(200),
  CEP INT,
  BAIRRO VARCHAR(100),
  PRIMARY KEY (IDCADASTRO)
  );
  