CREATE DATABASE DBEXERCICIO06;

USE DBEXERCICIO06;

CREATE TABLE PESSOA (
  IDPESSOA INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(100),
  IDADE INT ,
  RUA VARCHAR(45),
  NUMERO INT,
  BAIRRO VARCHAR(45),
  CIDADE VARCHAR(45),
  ESTADO VARCHAR(45),
  CEP CHAR(45),
  COMPLEMENTO VARCHAR(45),
  PRIMARY KEY (IDPESSOA)
  );